import { z } from "zod";

export const UiSelectionRectSchema = z.object({
  x: z.number(),
  y: z.number(),
  width: z.number(),
  height: z.number()
});

export const UiSelectionSourceSchema = z.object({
  file: z.string().optional(),
  component: z.string().optional(),
  line: z.number().int().positive().optional(),
  column: z.number().int().positive().optional()
});

export const UiSelectionSchema = z.object({
  url: z.string().min(1),
  title: z.string().optional(),
  tagName: z.string().min(1),
  text: z.string().optional(),
  ariaLabel: z.string().optional(),
  className: z.string().optional(),
  selector: z.string().optional(),
  nearbyHeading: z.string().optional(),
  rect: UiSelectionRectSchema,
  source: UiSelectionSourceSchema.optional(),
  selectedAt: z.number().int().positive()
});

export const ClientEventSchema = z.discriminatedUnion("type", [
  // The extension must send audio only. Transcripts are generated by the backend
  // through OpenAI audio transcription and returned as server events below.
  z.object({
    type: z.literal("session.configure"),
    backendUrl: z.string().url().optional(),
    projectPath: z.string().min(1),
    codexThreadId: z.string().min(1).optional()
  }),
  z.object({
    type: z.literal("audio.start"),
    sampleRate: z.number().int().positive(),
    format: z.enum(["pcm16", "webm-opus"])
  }),
  z.object({
    type: z.literal("audio.chunk"),
    data: z.string().min(1)
  }),
  z.object({
    type: z.literal("audio.stop")
  }),
  z.object({
    type: z.literal("codex.cancel")
  }),
  z.object({
    type: z.literal("codex.undo_last_change")
  }),
  z.object({
    type: z.literal("ui.selection.set"),
    selection: UiSelectionSchema
  })
]);

export const ServerStateSchema = z.enum([
  "disconnected",
  "ready",
  "listening",
  "processing",
  "codex_running",
  "needs_attention",
  "done",
  "error"
]);

export const FileChangeActionSchema = z.enum([
  "created",
  "updated",
  "deleted",
  "unknown"
]);

export const ServerEventSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("status"),
    state: ServerStateSchema,
    message: z.string()
  }),
  z.object({
    type: z.literal("transcript.partial"),
    text: z.string()
  }),
  z.object({
    type: z.literal("transcript.final"),
    text: z.string()
  }),
  z.object({
    type: z.literal("codex.thread"),
    threadId: z.string()
  }),
  z.object({
    type: z.literal("codex.progress"),
    message: z.string(),
    details: z.record(z.unknown()).optional()
  }),
  z.object({
    type: z.literal("codex.file_changed"),
    path: z.string(),
    action: FileChangeActionSchema
  }),
  z.object({
    type: z.literal("codex.approval_required"),
    message: z.string()
  }),
  z.object({
    type: z.literal("codex.done"),
    summary: z.string(),
    changedFiles: z.array(z.string()).default([]),
    undoAvailable: z.boolean().default(false)
  }),
  z.object({
    type: z.literal("codex.undo_available"),
    changedFiles: z.array(z.string()).default([])
  }),
  z.object({
    type: z.literal("codex.undo_completed"),
    message: z.string()
  }),
  z.object({
    type: z.literal("speech.audio"),
    text: z.string(),
    audio: z.string().min(1),
    mimeType: z.literal("audio/mpeg")
  }),
  z.object({
    type: z.literal("error"),
    code: z.string(),
    message: z.string(),
    recoverable: z.boolean().default(true),
    nextAction: z.string().optional()
  })
]);

export type ClientEvent = z.infer<typeof ClientEventSchema>;
export type ServerEvent = z.infer<typeof ServerEventSchema>;
export type ServerState = z.infer<typeof ServerStateSchema>;
export type FileChangeAction = z.infer<typeof FileChangeActionSchema>;
export type UiSelection = z.infer<typeof UiSelectionSchema>;
